version: 2.1

workflows:
  cypress:
    jobs:
      - run_dev
jobs:
  run_dev: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn dev
          name: Run dev
      - persist_to_workspace:
          root: ~/project
          paths: .
